export const PAISES = [
  { codigo: "ES", nombre: "España", prefijo: "+34" },
  { codigo: "AF", nombre: "Afganistán", prefijo: "+93" },
  { codigo: "AL", nombre: "Albania", prefijo: "+355" },
  { codigo: "DE", nombre: "Alemania", prefijo: "+49" },
  { codigo: "AD", nombre: "Andorra", prefijo: "+376" },
  { codigo: "AO", nombre: "Angola", prefijo: "+244" },
  { codigo: "AI", nombre: "Anguila", prefijo: "+1264" },
  { codigo: "AQ", nombre: "Antártida", prefijo: "+672" },
  { codigo: "AG", nombre: "Antigua y Barbuda", prefijo: "+1268" },
  { codigo: "SA", nombre: "Arabia Saudita", prefijo: "+966" },
  { codigo: "DZ", nombre: "Argelia", prefijo: "+213" },
  { codigo: "AR", nombre: "Argentina", prefijo: "+54" },
  { codigo: "AM", nombre: "Armenia", prefijo: "+374" },
  { codigo: "AW", nombre: "Aruba", prefijo: "+297" },
  { codigo: "AU", nombre: "Australia", prefijo: "+61" },
  { codigo: "AT", nombre: "Austria", prefijo: "+43" },
  { codigo: "AZ", nombre: "Azerbaiyán", prefijo: "+994" },
  { codigo: "BS", nombre: "Bahamas", prefijo: "+1242" },
  { codigo: "BH", nombre: "Baréin", prefijo: "+973" },
  { codigo: "BD", nombre: "Bangladés", prefijo: "+880" },
  { codigo: "BB", nombre: "Barbados", prefijo: "+1246" },
  { codigo: "BE", nombre: "Bélgica", prefijo: "+32" },
  { codigo: "BZ", nombre: "Belice", prefijo: "+501" },
  { codigo: "BJ", nombre: "Benín", prefijo: "+229" },
  { codigo: "BM", nombre: "Bermudas", prefijo: "+1441" },
  { codigo: "BY", nombre: "Bielorrusia", prefijo: "+375" },
  { codigo: "MM", nombre: "Birmania (Myanmar)", prefijo: "+95" },
  { codigo: "BO", nombre: "Bolivia", prefijo: "+591" },
  { codigo: "BA", nombre: "Bosnia y Herzegovina", prefijo: "+387" },
  { codigo: "BW", nombre: "Botsuana", prefijo: "+267" },
  { codigo: "BR", nombre: "Brasil", prefijo: "+55" },
  { codigo: "BN", nombre: "Brunéi", prefijo: "+673" },
  { codigo: "BG", nombre: "Bulgaria", prefijo: "+359" },
  { codigo: "BF", nombre: "Burkina Faso", prefijo: "+226" },
  { codigo: "BI", nombre: "Burundi", prefijo: "+257" },
  { codigo: "BT", nombre: "Bután", prefijo: "+975" },
  { codigo: "CV", nombre: "Cabo Verde", prefijo: "+238" },
  { codigo: "KH", nombre: "Camboya", prefijo: "+855" },
  { codigo: "CM", nombre: "Camerún", prefijo: "+237" },
  { codigo: "CA", nombre: "Canadá", prefijo: "+1" },
  { codigo: "QA", nombre: "Catar", prefijo: "+974" },
  { codigo: "TD", nombre: "Chad", prefijo: "+235" },
  { codigo: "CL", nombre: "Chile", prefijo: "+56" },
  { codigo: "CN", nombre: "China", prefijo: "+86" },
  { codigo: "CY", nombre: "Chipre", prefijo: "+357" },
  { codigo: "VA", nombre: "Ciudad del Vaticano", prefijo: "+379" },
  { codigo: "CO", nombre: "Colombia", prefijo: "+57" },
  { codigo: "KM", nombre: "Comoras", prefijo: "+269" },
  { codigo: "KP", nombre: "Corea del Norte", prefijo: "+850" },
  { codigo: "KR", nombre: "Corea del Sur", prefijo: "+82" },
  { codigo: "CI", nombre: "Costa de Marfil", prefijo: "+225" },
  { codigo: "CR", nombre: "Costa Rica", prefijo: "+506" },
  { codigo: "HR", nombre: "Croacia", prefijo: "+385" },
  { codigo: "CU", nombre: "Cuba", prefijo: "+53" },
  { codigo: "CW", nombre: "Curazao", prefijo: "+599" },
  { codigo: "DK", nombre: "Dinamarca", prefijo: "+45" },
  { codigo: "DM", nombre: "Dominica", prefijo: "+1767" },
  { codigo: "EC", nombre: "Ecuador", prefijo: "+593" },
  { codigo: "EG", nombre: "Egipto", prefijo: "+20" },
  { codigo: "SV", nombre: "El Salvador", prefijo: "+503" },
  { codigo: "AE", nombre: "Emiratos Árabes Unidos", prefijo: "+971" },
  { codigo: "ER", nombre: "Eritrea", prefijo: "+291" },
  { codigo: "SK", nombre: "Eslovaquia", prefijo: "+421" },
  { codigo: "SI", nombre: "Eslovenia", prefijo: "+386" },
  { codigo: "US", nombre: "Estados Unidos", prefijo: "+1" },
  { codigo: "EE", nombre: "Estonia", prefijo: "+372" },
  { codigo: "ET", nombre: "Etiopía", prefijo: "+251" },
  { codigo: "PH", nombre: "Filipinas", prefijo: "+63" },
  { codigo: "FI", nombre: "Finlandia", prefijo: "+358" },
  { codigo: "FJ", nombre: "Fiyi", prefijo: "+679" },
  { codigo: "FR", nombre: "Francia", prefijo: "+33" },
  { codigo: "GA", nombre: "Gabón", prefijo: "+241" },
  { codigo: "GM", nombre: "Gambia", prefijo: "+220" },
  { codigo: "GE", nombre: "Georgia", prefijo: "+995" },
  { codigo: "GH", nombre: "Ghana", prefijo: "+233" },
  { codigo: "GI", nombre: "Gibraltar", prefijo: "+350" },
  { codigo: "GD", nombre: "Granada", prefijo: "+1473" },
  { codigo: "GR", nombre: "Grecia", prefijo: "+30" },
  { codigo: "GL", nombre: "Groenlandia", prefijo: "+299" },
  { codigo: "GP", nombre: "Guadalupe", prefijo: "+590" },
  { codigo: "GU", nombre: "Guam", prefijo: "+1671" },
  { codigo: "GT", nombre: "Guatemala", prefijo: "+502" },
  { codigo: "GF", nombre: "Guayana Francesa", prefijo: "+594" },
  { codigo: "GN", nombre: "Guinea", prefijo: "+224" },
  { codigo: "GQ", nombre: "Guinea Ecuatorial", prefijo: "+240" },
  { codigo: "GW", nombre: "Guinea-Bisáu", prefijo: "+245" },
  { codigo: "GY", nombre: "Guyana", prefijo: "+592" },
  { codigo: "HT", nombre: "Haití", prefijo: "+509" },
  { codigo: "HN", nombre: "Honduras", prefijo: "+504" },
  { codigo: "HK", nombre: "Hong Kong", prefijo: "+852" },
  { codigo: "HU", nombre: "Hungría", prefijo: "+36" },
  { codigo: "IN", nombre: "India", prefijo: "+91" },
  { codigo: "ID", nombre: "Indonesia", prefijo: "+62" },
  { codigo: "IQ", nombre: "Irak", prefijo: "+964" },
  { codigo: "IR", nombre: "Irán", prefijo: "+98" },
  { codigo: "IE", nombre: "Irlanda", prefijo: "+353" },
  { codigo: "IS", nombre: "Islandia", prefijo: "+354" },
  { codigo: "BV", nombre: "Isla Bouvet", prefijo: "+47" },
  { codigo: "IM", nombre: "Isla de Man", prefijo: "+44" },
  { codigo: "CX", nombre: "Isla de Navidad", prefijo: "+61" },
  { codigo: "NF", nombre: "Isla Norfolk", prefijo: "+672" },
  { codigo: "AX", nombre: "Islas Åland", prefijo: "+358" },
  { codigo: "KY", nombre: "Islas Caimán", prefijo: "+1345" },
  { codigo: "CC", nombre: "Islas Cocos", prefijo: "+61" },
  { codigo: "CK", nombre: "Islas Cook", prefijo: "+682" },
  { codigo: "FO", nombre: "Islas Feroe", prefijo: "+298" },
  { codigo: "GS", nombre: "Islas Georgias del Sur", prefijo: "+500" },
  { codigo: "MH", nombre: "Islas Marshall", prefijo: "+692" },
  { codigo: "PN", nombre: "Islas Pitcairn", prefijo: "+64" },
  { codigo: "SB", nombre: "Islas Salomón", prefijo: "+677" },
  { codigo: "TC", nombre: "Islas Turcas y Caicos", prefijo: "+1649" },
  { codigo: "VG", nombre: "Islas Vírgenes Británicas", prefijo: "+1284" },
  { codigo: "VI", nombre: "Islas Vírgenes de EE. UU.", prefijo: "+1340" },
  { codigo: "IL", nombre: "Israel", prefijo: "+972" },
  { codigo: "IT", nombre: "Italia", prefijo: "+39" },
  { codigo: "JM", nombre: "Jamaica", prefijo: "+1876" },
  { codigo: "JP", nombre: "Japón", prefijo: "+81" },
  { codigo: "JE", nombre: "Jersey", prefijo: "+44" },
  { codigo: "JO", nombre: "Jordania", prefijo: "+962" },
  { codigo: "KZ", nombre: "Kazajistán", prefijo: "+7" },
  { codigo: "KE", nombre: "Kenia", prefijo: "+254" },
  { codigo: "KG", nombre: "Kirguistán", prefijo: "+996" },
  { codigo: "KI", nombre: "Kiribati", prefijo: "+686" },
  { codigo: "KW", nombre: "Kuwait", prefijo: "+965" },
  { codigo: "LA", nombre: "Laos", prefijo: "+856" },
  { codigo: "LS", nombre: "Lesoto", prefijo: "+266" },
  { codigo: "LV", nombre: "Letonia", prefijo: "+371" },
  { codigo: "LB", nombre: "Líbano", prefijo: "+961" },
  { codigo: "LR", nombre: "Liberia", prefijo: "+231" },
  { codigo: "LY", nombre: "Libia", prefijo: "+218" },
  { codigo: "LI", nombre: "Liechtenstein", prefijo: "+423" },
  { codigo: "LT", nombre: "Lituania", prefijo: "+370" },
  { codigo: "LU", nombre: "Luxemburgo", prefijo: "+352" },
  { codigo: "MO", nombre: "Macao", prefijo: "+853" },
  { codigo: "MK", nombre: "Macedonia del Norte", prefijo: "+389" },
  { codigo: "MG", nombre: "Madagascar", prefijo: "+261" },
  { codigo: "MY", nombre: "Malasia", prefijo: "+60" },
  { codigo: "MW", nombre: "Malaui", prefijo: "+265" },
  { codigo: "MV", nombre: "Maldivas", prefijo: "+960" },
  { codigo: "ML", nombre: "Malí", prefijo: "+223" },
  { codigo: "MT", nombre: "Malta", prefijo: "+356" },
  { codigo: "MA", nombre: "Marruecos", prefijo: "+212" },
  { codigo: "MQ", nombre: "Martinica", prefijo: "+596" },
  { codigo: "MU", nombre: "Mauricio", prefijo: "+230" },
  { codigo: "MR", nombre: "Mauritania", prefijo: "+222" },
  { codigo: "YT", nombre: "Mayotte", prefijo: "+262" },
  { codigo: "MX", nombre: "México", prefijo: "+52" },
  { codigo: "FM", nombre: "Micronesia", prefijo: "+691" },
  { codigo: "MD", nombre: "Moldavia", prefijo: "+373" },
  { codigo: "MC", nombre: "Mónaco", prefijo: "+377" },
  { codigo: "MN", nombre: "Mongolia", prefijo: "+976" },
  { codigo: "ME", nombre: "Montenegro", prefijo: "+382" },
  { codigo: "MS", nombre: "Montserrat", prefijo: "+1664" },
  { codigo: "MZ", nombre: "Mozambique", prefijo: "+258" },
  { codigo: "NA", nombre: "Namibia", prefijo: "+264" },
  { codigo: "NR", nombre: "Nauru", prefijo: "+674" },
  { codigo: "NP", nombre: "Nepal", prefijo: "+977" },
  { codigo: "NI", nombre: "Nicaragua", prefijo: "+505" },
  { codigo: "NE", nombre: "Níger", prefijo: "+227" },
  { codigo: "NG", nombre: "Nigeria", prefijo: "+234" },
  { codigo: "NU", nombre: "Niue", prefijo: "+683" },
  { codigo: "NO", nombre: "Noruega", prefijo: "+47" },
  { codigo: "NC", nombre: "Nueva Caledonia", prefijo: "+687" },
  { codigo: "NZ", nombre: "Nueva Zelanda", prefijo: "+64" },
  { codigo: "OM", nombre: "Omán", prefijo: "+968" },
  { codigo: "NL", nombre: "Países Bajos", prefijo: "+31" },
  { codigo: "PK", nombre: "Pakistán", prefijo: "+92" },
  { codigo: "PW", nombre: "Palaos", prefijo: "+680" },
  { codigo: "PS", nombre: "Palestina", prefijo: "+970" },
  { codigo: "PA", nombre: "Panamá", prefijo: "+507" },
  { codigo: "PG", nombre: "Papúa Nueva Guinea", prefijo: "+675" },
  { codigo: "PY", nombre: "Paraguay", prefijo: "+595" },
  { codigo: "PE", nombre: "Perú", prefijo: "+51" },
  { codigo: "PF", nombre: "Polinesia Francesa", prefijo: "+689" },
  { codigo: "PL", nombre: "Polonia", prefijo: "+48" },
  { codigo: "PT", nombre: "Portugal", prefijo: "+351" },
  { codigo: "PR", nombre: "Puerto Rico", prefijo: "+1" },
  { codigo: "GB", nombre: "Reino Unido", prefijo: "+44" },
  { codigo: "CF", nombre: "República Centroafricana", prefijo: "+236" },
  { codigo: "CZ", nombre: "República Checa", prefijo: "+420" },
  { codigo: "CD", nombre: "República Democrática del Congo", prefijo: "+243" },
  { codigo: "DO", nombre: "República Dominicana", prefijo: "+1809" },
  { codigo: "CG", nombre: "República del Congo", prefijo: "+242" },
  { codigo: "RE", nombre: "Reunión", prefijo: "+262" },
  { codigo: "RW", nombre: "Ruanda", prefijo: "+250" },
  { codigo: "RO", nombre: "Rumanía", prefijo: "+40" },
  { codigo: "RU", nombre: "Rusia", prefijo: "+7" },
  { codigo: "EH", nombre: "Sahara Occidental", prefijo: "+212" },
  { codigo: "WS", nombre: "Samoa", prefijo: "+685" },
  { codigo: "AS", nombre: "Samoa Americana", prefijo: "+1684" },
  { codigo: "BL", nombre: "San Bartolomé", prefijo: "+590" },
  { codigo: "KN", nombre: "San Cristóbal y Nieves", prefijo: "+1869" },
  { codigo: "SM", nombre: "San Marino", prefijo: "+378" },
  { codigo: "MF", nombre: "San Martín", prefijo: "+590" },
  { codigo: "PM", nombre: "San Pedro y Miquelón", prefijo: "+508" },
  { codigo: "VC", nombre: "San Vicente y las Granadinas", prefijo: "+1784" },
  { codigo: "SH", nombre: "Santa Elena", prefijo: "+290" },
  { codigo: "LC", nombre: "Santa Lucía", prefijo: "+1758" },
  { codigo: "ST", nombre: "Santo Tomé y Príncipe", prefijo: "+239" },
  { codigo: "SN", nombre: "Senegal", prefijo: "+221" },
  { codigo: "RS", nombre: "Serbia", prefijo: "+381" },
  { codigo: "SC", nombre: "Seychelles", prefijo: "+248" },
  { codigo: "SL", nombre: "Sierra Leona", prefijo: "+232" },
  { codigo: "SG", nombre: "Singapur", prefijo: "+65" },
  { codigo: "SX", nombre: "Sint Maarten", prefijo: "+1721" },
  { codigo: "SY", nombre: "Siria", prefijo: "+963" },
  { codigo: "SO", nombre: "Somalia", prefijo: "+252" },
  { codigo: "LK", nombre: "Sri Lanka", prefijo: "+94" },
  { codigo: "SZ", nombre: "Suazilandia (Esuatini)", prefijo: "+268" },
  { codigo: "ZA", nombre: "Sudáfrica", prefijo: "+27" },
  { codigo: "SD", nombre: "Sudán", prefijo: "+249" },
  { codigo: "SS", nombre: "Sudán del Sur", prefijo: "+211" },
  { codigo: "SE", nombre: "Suecia", prefijo: "+46" },
  { codigo: "CH", nombre: "Suiza", prefijo: "+41" },
  { codigo: "SR", nombre: "Surinam", prefijo: "+597" },
  { codigo: "TH", nombre: "Tailandia", prefijo: "+66" },
  { codigo: "TW", nombre: "Taiwán", prefijo: "+886" },
  { codigo: "TZ", nombre: "Tanzania", prefijo: "+255" },
  { codigo: "TJ", nombre: "Tayikistán", prefijo: "+992" },
  { codigo: "IO", nombre: "Territorio Británico del Océano Índico", prefijo: "+246" },
  { codigo: "TF", nombre: "Territorios Australes Franceses", prefijo: "+262" },
  { codigo: "TL", nombre: "Timor Oriental", prefijo: "+670" },
  { codigo: "TG", nombre: "Togo", prefijo: "+228" },
  { codigo: "TK", nombre: "Tokelau", prefijo: "+690" },
  { codigo: "TO", nombre: "Tonga", prefijo: "+676" },
  { codigo: "TT", nombre: "Trinidad y Tobago", prefijo: "+1868" },
  { codigo: "TN", nombre: "Túnez", prefijo: "+216" },
  { codigo: "TM", nombre: "Turkmenistán", prefijo: "+993" },
  { codigo: "TR", nombre: "Turquía", prefijo: "+90" },
  { codigo: "TV", nombre: "Tuvalu", prefijo: "+688" },
  { codigo: "UA", nombre: "Ucrania", prefijo: "+380" },
  { codigo: "UG", nombre: "Uganda", prefijo: "+256" },
  { codigo: "UY", nombre: "Uruguay", prefijo: "+598" },
  { codigo: "UZ", nombre: "Uzbekistán", prefijo: "+998" },
  { codigo: "VU", nombre: "Vanuatu", prefijo: "+678" },
  { codigo: "VE", nombre: "Venezuela", prefijo: "+58" },
  { codigo: "VN", nombre: "Vietnam", prefijo: "+84" },
  { codigo: "WF", nombre: "Wallis y Futuna", prefijo: "+681" },
  { codigo: "YE", nombre: "Yemen", prefijo: "+967" },
  { codigo: "DJ", nombre: "Yibuti", prefijo: "+253" },
  { codigo: "ZM", nombre: "Zambia", prefijo: "+260" },
  { codigo: "ZW", nombre: "Zimbabue", prefijo: "+263" },
] as const;

export type CodigoPais = (typeof PAISES)[number]["codigo"];

export function prefijoPais(codigo: string) {
  return PAISES.find((p) => p.codigo === codigo)?.prefijo ?? "+34";
}

export function banderaPais(codigo: string) {
  if (!/^[A-Z]{2}$/.test(codigo)) return "🏳️";
  const puntos = [...codigo].map((letra) => 127397 + letra.charCodeAt(0));
  return String.fromCodePoint(...puntos);
}
